### ISSUE TITLE
React 18 support - peerDependencies update request

### ISSUE THREAD

**Issue by mezei** [AaronCCWong/react-card-flip#100]
Hello!

I'm currently using this package in an app I just upgraded to React 18. It seems to work fine, however it complains about its peerDependencies as it's set to React 17.

Could the peerDependencies be updated to be a bit more lax and allow newer versions of react & react-dom as well?

Thank you!

**Comment by rayraspberry** [comment]
I believe this issue would be resolved by merging in pull 98
https://github.com/AaronCCWong/react-card-flip/pull/98

**Comment by AaronCCWong** [comment]
#98 isnt going to cut it. Enzyme didn't yet support React 18 when 18 was released which is why I've held off on updating but since it appears there are no plans for enzyme to support React 18 (https://dev.to/wojtekmaj/enzyme-is-dead-now-what-ekl) it might make sense to move over to react-testing-library in conjunction with upgrading to react 18. Would definitely appreciate a PR to do this. Otherwise, I'll try to make time to get to this.

**Comment by AaronCCWong** [comment]
Thanks @dododevs for add React 18 support. Latest release has been published to npm.
