### ISSUE TITLE
card is not visible in the middle of the animation

### ISSUE THREAD

**Issue by calvin17** [AaronCCWong/react-card-flip#47]
I have implemented the react-card-flip while implementing it is animating perfectly,
but some days before, it is not working. In the middle of the animation card disappears for sometime.

**Comment by AaronCCWong** [comment]
Could you provide a JSFiddle that reproduces this bug?

**Comment by calvin17** [comment]
I am using chrome, facing the same issue even in official example url(https://aaronccwong.github.io/react-card-flip/). It is not working in recent version of chrome Version 75.0.3770.90. It was working in Version 74.

**Comment by andycloke** [comment]
same issue here on chome: `Version 75.0.3770.100 (Official Build) (64-bit)`

**Comment by AaronCCWong** [comment]
https://github.com/AaronCCWong/react-card-flip/commit/47f24ed2e7410425dc35b010be0f451333abd174 fixes this issue.

**Comment by Taelkir** [comment]
I think I'm still experiencing this in Chrome 76 - no such issue in Firefox 68. It's one of those things that happens "sometimes", so I feel like it might be related to page performance, but it only happens when moving from front to back.
![2019-07-31_15-33-49](https://user-images.githubusercontent.com/36701898/62221924-60b81600-b3aa-11e9-8530-ad1f701ce5dc.gif)
