### ISSUE TITLE
Why the default to position absolute ?

### ISSUE THREAD

**Issue by wilomgfx** [AaronCCWong/react-card-flip#7]
Kinda messes with my layout. I feel this component should be not positioned from the intern of the library itself. I'll have to remove that position absolute with !important 📦 

Other than that, great reusable component.

One thing would be cool would be to modify the transform speed and animation.

**Comment by lotusms** [comment]
I brought up this issue before. My transform/animation wasn't showing. The author fixed it (great stuff) but I did mention, that if the transform/animation would be more accessible, it could be handled and adjusted instead of hardcoded in. Not a big deal in my opinion since the animation speed is nice but some people may have a need for a different transform or even a faster/slower animation speed.

**Comment by AaronCCWong** [comment]
Making animation speed more dynamic would be a great addition to this component. I can work on it this weekend. I will also welcome a PR.

**Comment by AaronCCWong** [comment]
As for position absolute, at least side of the card must have position absolute applied so that it doesn't fill the space. If not you will have this weird animation where when the card flips, one side of the card appears below where the card should be.

**Comment by wilomgfx** [comment]
Indeed that's what i noticed. No problem there, its easily fixed by overriding that back to `position: static`

**Comment by Emisu2** [comment]
When I flip a card displayed as in-line block, there is space that appears underneath of it, and all the other cards move/change position/drop down.  Wondered if anyone else has seen this because I can't explain it and have tried playing with position properties such as static but no luck...  Inspecting the elements hasn't helped.  Thanks.
![image](https://user-images.githubusercontent.com/52388125/61982344-756f6500-afca-11e9-8c05-26797b7679aa.png)

**Comment by Emisu2** [comment]
For what it's worth, I just tried it removing all card content, and now it's working properly...  Must have something to do with my card content or styling.  I'll keep trying.  Thanks.
